def with_catch
  yield
rescue Exception => e
  p "////////////////////////////////////////////////////////////////////////////"
  p e.message
  p e.backtrace
  p "////////////////////////////////////////////////////////////////////////////"
  status 500
end